### PR TITLE
feat: initial orb release [semver:major]

### PR DESCRIPTION
**Pull request by KyleTryon**
# v1.0.0

Lint your commit messages in a CircleCI job.

Add this orb's `commitlint/lint` job to your existing CircleCI workflow to utilize [commitlint](https://github.com/conventional-changelog/commitlint) for validating commit messages against the [conventional commit format](https://conventionalcommits.org/).

Preview: https://circleci.com/developer/orbs/orb/conventional-changelog/commitlint?version=dev:alpha
Live link (after merge): https://circleci.com/developer/orbs/orb/conventional-changelog/commitlint

## Config Example

This example shows importing the `commitlint` orb into a basic CircleCI 2.1 config file, and adding the `commitlint/lint` job to a workflow. This configuration will lint every commit pushed to the repository.

```yaml
version: 2.1
  orbs:
    commitlint: conventional-changelog/commitlint@1.0
  workflows:
    my-workflow:
      jobs:
        - commitlint/lint
```

## Live Test Example

CircleCI Job: https://app.circleci.com/pipelines/github/conventional-changelog/commitlint-orb/5/workflows/a3344c6e-54ae-447f-8e31-6dbf9964d55d/jobs/13

image

## How does it work?
Ideally, a branch or PR should (in most cases) contain only a single commit message. However, the commitlint orb will utilize `git cherry` to find all commits in the current branch that are unique from the target branch (`main` by default). Each commit message will then be sent to commitlint and the job will exit on the first failure.

To resolve the issue, amend your commit message, and rebase/squash your branch if needed.

## What parameters are avalable?

```yaml
config-path:
    type: string
    description: Path to commitlint config file
    default: "./commitlint.config.js"
  configs:
    type: string
    description: A space-separated list of commitlint config packages to install.
    default: "@commitlint/config-conventional"
  target-branch:
    type: string
    description: Commits in the current branch will be compared against the target branch for linting. All commits not present in the target branch will be linted.
    default: "main"
  node-version:
    type: string
    default: "16.5.0"
    description: "Specifiy the NodeJS version used to run the commitlint job. This should not usually need to be changed."
```

## Why is `[semver:major]` in the PR title?
Currently, orbs on CircleCI look for this special semantic tag in the commit message in order to know what type of deployment to produce. In the near future, thanks in part to the creation of this commitlint orb, CircleCI will be able to switch to using purely conventional commit messages for versioning. When the next version of CircleCI's orb-tools is released, it will be possible to update this repo's config and no longer need to use `[semver:increment]` tags.

### CODE REVIEW

**Comment by escapedcat** [comment]
LGTM, thanks for your work @KyleTryon !

**Review by escapedcat — APPROVED** [review]

**Comment by AdeAttwood** [comment]
@KyleTryon sorry this has taken so long. For me, there are a few cases missing. This will not lint the body and only works on PR's. I have been playing with bats and come up with a test suite that I think will be a good first step. I put the tests in a  new branch, then we can work from there. I think it would be a good idea to add in the bats jobs back in to validate any other issues.

**Comment by KyleTryon** [comment]
> @KyleTryon sorry this has taken so long. For me, there are a few cases missing. This will not lint the body and only works on PR's. I have been playing with bats and come up with a test suite that I think will be a good first step. I put the tests in a new branch, then we can work from there. I think it would be a good idea to add in the bats jobs back in to validate any other issues.

Not a problem at all 🙇 thanks for the review. Also a huge fan of BATS, I [use it in several orbs as well](https://github.com/CircleCI-Public/slack-orb/blob/master/src/tests/notify.bats), and we can certainly add it here too. I took a look for the branch but I am assuming it hasn't been pushed yet.

What did you mean by this only working for PRs? This _should_ work on any commit to the repo on any branch (at least as depicted in the usage example above, more filters can be added).

You also mentioned this was not currently linting the body of the commit message. If you could provide an example of the command you would use to lint the full commit I'll get that update added, You may already have the check for this in your tests 👍

**Comment by AdeAttwood** [comment]
I have now pushed up the [branch](https://github.com/conventional-changelog/commitlint-orb/tree/working-on-tests).  

Sorry bad wording, what I mean by "only working for PRs?" is that I was getting errors when the current branch (CIRCLE_BRANCH) is the same as the target branch (CL_PARAM_TARGET_BRANCH). When the current branch and target branch is different that is when we will be in a PR situation, that is where I got that from.

The other test I think is important to ensure passes is the [test to lint the body](https://github.com/conventional-changelog/commitlint-orb/blob/working-on-tests/src/tests/lint.bats#L52), I was getting of results on this one to.

There are various other tests, let me know what you think.

**Comment by KyleTryon** [comment]
Closing in favor of a new PR #3

**Pull request closed without merging**
